version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "hens-and-roosters"
        POSTGRES_PASSWORD: "postgres"
    ports:
        - 5431:5432
  backend:
    image: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
        DB_HOST: db
        DB_USER: "postgres"
        DB_PASSWORD: "postgres"
  frontend:
    image: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    environment:
      BACKEND_URL: http://localhost:3000
  test:
    image: backend
    build: ./backend
    depends_on:
      - backend
    tty: true
    stdin_open: true
    command: sh -c "sleep 10 && yarn test"
    environment:
        DB_HOST: db
        DB_USER: "postgres"
        DB_PASSWORD: "postgres"