apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/hens-and-roosters-2/frontend
        name: frontend
        resources:
            limits:
              memory: "1500Mi"
              cpu: "1.0"
            requests:
              memory: "500Mi"
              cpu: "0.5"
        env:
          - name: BACKEND_URL
            value: "https://hens-and-roosters.tk"
          - name: AZURE_KEY
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: azure_key
          - name: GIPHY_KEY
            valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: giphy_key
          - name: NEWS_URL
            value: "https://hensandroosters.cognitiveservices.azure.com/bing/v7.0/news"


---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - name: "http-port"
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: frontend
